# Generated by Django 5.0.3 on 2024-03-26 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='end_date_time',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='start_date_time',
            new_name='start_time',
        ),
    ]
