# Generated by Django 5.0.3 on 2024-03-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_booking_client_alter_booking_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='beds',
            field=models.PositiveIntegerField(),
        ),
    ]
