# Generated by Django 5.0.3 on 2024-03-31 07:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_room_beds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='cost_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
